# Generated by Django 4.2 on 2023-05-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_menuitem_is_root'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='named_url',
        ),
    ]
